#build flask app 
FROM python:3.7.3-stretch

#set working directory
WORKDIR /app
#copy all files from current directory to working directory
COPY . /app
#copy ../model/nargsLossCalculation.py to working directory
COPY ../model/nargsLossCalculation.py /app
#install dependencies
RUN pip install -r requirements.txt
#expose port 8080
EXPOSE 8080
#run flask app


CMD ["python", "app.py"]