version: "3"
services:
  vis:
    image: st7ma784/vis
    container_name: vis
    ports:
      - 5000:5000
    expose:
      - 5000
    restart: always
    networks:
      - vis
    
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 vis
    restart: always

networks:
  vis:
    driver: bridge  
    

