#build flask app 
FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime
COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt

#set working directory
WORKDIR /app
#copy all files from current directory to working directory
COPY . /app
#copy ../model/nargsLossCalculation.py to working directory
#install dependencies
#expose port 8080
EXPOSE 5000/tcp

ENTRYPOINT ["python", "app.py"]