version: "3"
services:
  vis:
    image: st7ma784/vislsa:latest
    container_name: vis
    restart: always
    ports:
    # open port 5000 on host to port 5000 
      - "5000:5000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  demo: 
    image: st7ma784/vis:latest
    container_name: demo
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
    # open port 5001 on host to port 5000 
      - "5001:5000"

# create nginx container
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - vis
      - demo
    ports:
    # open port 80 on host to port 80 
      - "80:80"
    volumes:
    # mount nginx config file
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 vis
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always


